Repository boostcampaitech3/final-project-level3-cv-01, pull requests merged in 2022-06, with the labels that each got.

#92 refactor : .idea 삭제
  .idea/.gitignore
  .idea/cropdetection.iml
  .idea/deployment.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/modules.xml
Labels: refactor

#97 refactor : backend 패키지화
  Backend/main.py
  backend/.gitignore
  backend/README.md
  backend/database.csv
  backend/main.py
  backend/schema.py
  backend/utills/S3_file_management.py
  backend/utills/cls_kind.py
  backend/utills/getS3contents.py
  backend/utills/memo.py
  backend/utills/weather.py
Labels: backend, refactor

#94 docs : Update README
  README.md
  model/utils/.DS_Store
  model/utils/Notebook/.DS_Store
Labels: documentation
